# -*- coding: utf-8 -*-
"""RESNET.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HQekMl-38dNxZtuGskCBf3g90tuoxf0b
"""

class ResnetBlock(nn.Module):
    def __init__(self, indim,outdim, use_dropout,require_downsampling):
        super(ResnetBlock, self).__init__()
        self.indim=indim
        self.outdim=outdim
        self.conv_block = self.build_conv_block(indim,outdim,use_dropout,require_downsampling)
        if indim!=outdim and require_downsampling==True :
          self.resconv = nn.Sequential(nn.Conv2d(indim, outdim, kernel_size=3,stride=2),
                       nn.BatchNorm2d(outdim),
                       nn.ReLU(True))
          
        if indim!=outdim and require_downsampling==False  :
          self.resconv = nn.Sequential(nn.Conv2d(indim, outdim, kernel_size=1,stride=1),
                       nn.BatchNorm2d(outdim),
                       nn.ReLU(True))  

    def build_conv_block(self, indim, outdim, use_dropout,require_downsampling):
        conv_block = []
        if require_downsampling==True :
          conv_block += [nn.Conv2d(indim, outdim, kernel_size=3,stride=2),
                       nn.BatchNorm2d(outdim),
                       nn.ReLU(True)]
        else :
          conv_block += [nn.Conv2d(indim, outdim, kernel_size=1,stride=1),
                       nn.BatchNorm2d(outdim),
                       nn.ReLU(True)]


        conv_block += [nn.Conv2d(outdim, outdim, kernel_size=3, padding=1),
                       nn.BatchNorm2d(outdim),
                       nn.ReLU(True)]   

        conv_block += [nn.Conv2d(outdim, outdim, kernel_size=1),
                       nn.BatchNorm2d(outdim),
                       nn.ReLU(True)]                           

        if use_dropout:
            conv_block += [nn.Dropout(0.5)]

        return nn.Sequential(*conv_block)

    def forward(self, x):
        out = self.conv_block(x)
        if self.indim!=self.outdim  :
          x = self.resconv(x)
        out = x + out
        return out